services:

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - ${FRONTEND_PORT}:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - ${BACKEND_PORT}:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app

  db:
    image: postgres
    environment:
      - POSTGRES_DB=site_ao
      - POSTGRES_USER=site_ao
      - POSTGRES_PASSWORD=pwd
    volumes:
      - pg_dev:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pg_dev:
